scrape_configs:
  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://host.docker.internal:6001/health #Catalog API
        - http://host.docker.internal:6002/health #Loan API
 #      - http://loan:8080/health # loan-api
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: 'postgres-metrics'
    static_configs:
      - targets: ['postgres:5432']
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
    - targets: ['otel-collector:8889']
    - targets: ['otel-collector:8888']
  - job_name: 'loan-api'
    metrics_path: '/metrics'
    scrape_interval: 10s    
    scheme: http
    static_configs:    
    - targets: ['loan:8080']
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']  # Adjust this depending on your setup    